### PR TITLE
Windows blocking

### PR DESCRIPTION
**Pull request by nponeccop**
This PR fixes a 12 years old issue https://rt.cpan.org/Public/Bug/Display.html?id=21751

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @nponeccop! Thanks for looking into this.

Unfortunately this isn't (as far as I can remember?!) the primary upstream repository for this library. I honestly don't remember why I have this in my account... I assume I migrated it from the original Subversion repository at some point for a project I was working on.

I believe this library is currently lacking a maintainer, though @bradfitz (who made all but one of the CPAN releases to date) may be able to correct me on that and point you to a suitable upstream repository to submit this change through.

**Comment by nponeccop** [comment]
Yep I know it's not the official repo. But I need one to build my custom package from. I also crossposted on rt, registered a handle and uploaded an unofficial release https://metacpan.org/release/NML/Danga-Socket-1.62-TRIAL so it's best we can do given that @bradfitz is apparently busy.

Another maintainer is https://www.linkedin.com/in/baudehlo/ which seems to be the same as @baudehlo.

I'd like to get some permissions but I have no idea on how to ask. @bradfitz is active on GitHub so let's hope he reads and has time to respond.

**Comment by baudehlo** [comment]
Happy to hand over maintenance on cpan if I have some kind of ownership of this (it’s been forever and I have no idea). Give me a pause id and I’ll contact the right people.

**Comment by nponeccop** [comment]
My pause id is `NML`

**Comment by baudehlo** [comment]
Ok can’t do it via pause. Sent a message to the admins.

**Comment by nponeccop** [comment]
@baudehlo Any news?

**Comment by nponeccop** [comment]
@baudehlo any news? I send an email to @bradfitz

**Comment by nponeccop** [comment]
Ok guys, Brad gave me the permissions. Now I'll release one more trial to ensure that my release process hasn't broken since, and release it officially after a week on CPAN Testers.

**Comment by nponeccop** [comment]
Closing as I've released this code on CPAN and it's on my fork's master branch now, properl tagged as `1.62`

**Pull request closed without merging**
